# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup 
## changed! - Setup
title:            Yun's Recorder 
tagline:          'dev'
description:      'Be sensitive to chance, be ready to transform - philip kotler'
#url:              

author:
  ## changed! - name
  name:           'Yunjeong Cho'
  #url:            

paginate:         5

# Custom vars
version:          2.0.0

## changed! - github address 
github:
  repo:           https://github.com/whdbswjd89
