# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Yun's recoder 
tagline:          'A Jekyll Theme'
description:      'Talk is cheap,Show me the code - Linus Benedict Torvalds'
#url:             

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         10

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
