# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Yun's recoder 
tagline:          'A Jekyll theme'
description:      'Time flowing'
#url:              http://lanyon.getpoole.com

author:
  name:           'Yun'
  #url:            

paginate:         10

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/whdbswjd89