title: Yun's recoder
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://whdbswjd89.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5   # 한페이지에 출력할 글 갯수

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Categories
   url: /categories

social:
   github: whdbswjd89
   email: whdbswjd89@gmail.com

google_analytics: ""
